site_name: ICOS ATC Documentation
nav: 
  - Home: index.md
  - 'Datavisualization toolchain':
    - 'Introduction': dtvs1.md
    - 'Installation': dtvs2.md
    - 'Documentation' :
      - 'JavaScript': dtvs3.md
      - 'Python' : dtvs4.md
    - 'JavaScript module documentation' : dtvs-js/index.html
  - 'Website':
    - 'Panelboards': pnb1.md
    - 'People': people.md
theme: readthedocs
